-- Load plugin modules in order.

require("plugins.whichkey")
require("plugins.colorscheme")
require("plugins.todo-comments")
require("plugins.mini")
require("plugins.snacks")
require("plugins.toggleterm")
require("plugins.telescope")
require("plugins.markview")
require("plugins.lspconfig")
require("plugins.nvim-tree")
require("plugins.blink")
require("plugins.treesitter")
require("plugins.nvim-ufo")
